services:
  web:
    build: ./server
    working_dir: /usr/src/app/project
    command: uwsgi --socket 0.0.0.0:5000 --enable-threads --protocol=http -w wsgi:app --logto /dev/stdout --workers 4 --threads 2
    volumes:
      - ./database/:/usr/src/app/project/instance:z
      - ./logs:/usr/src/app/project/logs:z
      #     - ./config:/usr/src/app/project/config
    ports:
      - 5000:5000

 # proxy:
 #   image: nginx:stable-alpine
 #   container_name: proxy
 #   depends_on:
 #     - web
 #   volumes:
 #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
 #     - ./certs:/etc/letsencrypt  
 #   ports:
 #     - "80:80"
 #     - "443:443"
 #   restart: always
#
 # certbot:
 #   image: certbot/certbot
 #   container_name: certbot
 #   volumes:
 #     - ./certs:/etc/letsencrypt
 #     - ./nginx.conf:/etc/nginx/nginx.conf
 #   depends_on:
 #     - proxy
 #   entrypoint: /bin/sh
 #   command: -c "certbot certonly --webroot -w /usr/src/app/letsencrypt -d mealmaster.noip.at --email admin@mail.de --agree-tos --no-eff-email"